def generate_report(description, root_cause, risk_level, capa):

    report = f"""
INCIDENT INVESTIGATION REPORT
-------------------------------------

1. Incident Description
{description}

2. Root Cause Analysis
{root_cause}

3. Risk Assessment
Risk Level: {risk_level}

4. Corrective Action
{capa['corrective']}

5. Preventive Action
{capa['preventive']}

6. Responsible Person
{capa['responsible']}

7. Target Completion Date
{capa['target_date']}

8. Action Status
{capa['status']}

9. Investigation Timeline
Incident Reported : Immediate
Investigation Started : Within 24 hrs
Root Cause Identified : Within 48 hrs
CAPA Implementation : Within 7 days

10. Monitoring & Follow Up
Safety team will review effectiveness of corrective actions.

-------------------------------------
Generated by AI Incident Investigation Assistant
"""

    return report
